---
title: "Small Mammal Bios"
author: "Kate Culhane"
date: "March 5, 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

# Load necessary packages

library(tidyverse)
library(gt) # making pretty tables
library(ape) # phylogenetic analysis
library(ggtree) # ggplot phylogenetic trees
library(ggwaffle) # ggplot waffle plots
library(emojifont) # emojis for waffle plot icons

# Load necessary data

smamms <- read_csv('./data/unique_smamms.csv') # dataset with one row per unique individual

bio <- read_csv('./data/smamm_bio.csv') # small mammal biographies

traits <- read_csv('./data/trait.csv') # small mammal functional traits

tree <- read.nexus('./data/Small_phylogeny.nex') # phylogenetic tree

```

###Photos

**Credits:**

- SPBE: https://www.inaturalist.org/photos/18567882
- PEBO: https://www.inaturalist.org/observations/283652
- PETR: https://www.inaturalist.org/observations/7461632
- REME: https://www.inaturalist.org/photos/162514
- SOTR: https://www.inaturalist.org/observations/14469602
- TAQU: https://www.inaturalist.org/observations/16497360
- TASE: https://www.inaturalist.org/observations/3534880
- GLSA: https://www.inaturalist.org/photos/4120147

###Table of characteristics

```{r}

bio %>% 
  filter(code == 'PEMA') %>% # FILTER FOR SMAMM
  gather(info, value, 2:8) %>% 
  select(-code) %>% 
  gt() %>% 
  tab_header(
    title = md('**Mammal Information**')
  ) %>% 
  cols_label(info = '', value = '') %>% 
  tab_style(
    style = cells_styles(text_weight = 'bold'),
    locations = cells_data(
      columns = vars(info)
    )
  ) %>% 
  tab_style(
    style = cells_styles(text_style = 'italic'),
    locations = cells_data(
      columns = vars(value),
      rows = 4
    )
  ) %>% 
  tab_options(
    table.width = px(500)
  )

```


###Pie chart of diet

```{r}

diet <- traits %>% 
  gather('diet_item', 'prop', 4:9) %>% 
  select(code, diet_item, prop)

colors <- c('darkgoldenrod3', 'cadetblue4', 'darkolivegreen4', 'navajowhite3', 'olivedrab3', 'coral3')
names(colors) <- as.character(unique(diet$diet_item))
labs <- c('Seeds', 'Fruits', 'Vegetation', 'Fungi', 'Invertebrates', 'Vertebrates')
names(labs) <- as.character(unique(diet$diet_item))

diet %>% 
  filter(code == 'GLSA',
         prop != 0) %>% 
  arrange(-prop) %>% 
  mutate(diet_item = factor(diet_item, levels = diet_item)) %>% 
  arrange(prop) %>% 
  ggplot(aes(x = code, y = prop)) +
    geom_bar(aes(fill = diet_item),
             stat = 'identity',
             color = 'white',
             lwd = 3) +
    geom_text(aes(x = 1.6,
                  label = paste0(prop, '%')),
              position = position_stack(vjust = 0.5),
              size = 4.3, fontface = 'bold') +
    scale_fill_manual('Diet Item',
                      values = colors,
                      labels = labs) +
    coord_polar(theta = 'y', start = 1) +
    theme_minimal() +
    theme(axis.title.x = element_blank(),
          axis.title.y = element_blank(),
          panel.border = element_blank(),
          panel.grid = element_blank(),
          axis.text.x = element_blank(),
          axis.text.y = element_blank())

```


###Phylogeny

```{r}

# Format phylogeny

phylo <- tree[[1]]

# Update binomial format (remove spaces)

smamms <- smamms %>% 
  mutate(binomial_new = gsub(' ', '_', binomial))

# Trim tree

species <- unique(smamms$binomial_new) %>% 
  append(., c('Puma_concolor', 'Canis_latrans', 'Didelphis_virginiana', 'Lynx_rufus', 'Spilogale_gracilis', 'Mephitis_mephitis', 'Odocoileus_hemionus', 'Urocyon_cinereoargenteus', 'Ursus_americanus', 'Lepus_townsendii', 'Homo_sapiens'))

pruned <- drop.tip(phylo, phylo$tip.label[-match(species, phylo$tip.label)])

write.nexus(pruned, file = './data/pruned_tree.nex')

pruned <- read.nexus('./data/pruned_tree.nex') # phylogenetic tree

# Create phylogram

pruned_grouped <- groupClade(pruned, c(25,26,35))

phylo_labels <- data.frame(label = pruned_grouped$tip.label,
                     name = c('Virgina opossum', 'Mountain lion', 'Bobcat', 'Gray fox', 'Coyote', 'Spotted skunk', 'Striped skunk', 'American black bear', 'Mule deer', 'Trowbridge\'s shrew', 'Human', 'California ground squirrel', 'Shadow chipmunk', 'Yellow pine chipmunk', 'Long-eared chipmunk', 'Northern flying squirrel', 'Dusky-footed woodrat', 'Brush mouse', 'Pinyon mouse', 'North American deer mouse', 'Western harvest mouse', 'White-tailed jackrabbit'),
                     code = c('', '', '', '', '', '', '', '', '', 'SOTR', '', 'SPBE', 'TASE', 'TAAM', 'TAQU', 'GLSA', 'NEFU', 'PEBO', 'PETR', 'PEMA', 'REME', '')) %>% # data frame for labels
  mutate(match = grepl('PEMA', code)) # FILTER FOR SMAMM

ggtree(pruned_grouped, aes(color = group),
       size = 1.4) %<+% phylo_labels +
  scale_color_manual(values = c('grey60', 'black', 'grey60', 'black')) +
  
  geom_tiplab(aes(label = name,
                  alpha = factor(match)),
              offset = 2,
              geom = 'label',
              fill = 'coral2', color = NA) +
  scale_alpha_manual(values = c(0, 1)) +
  geom_tiplab(aes(label = name), offset = 3) +
  geom_rootedge(rootedge = 10, size = 1.4) +
  xlim(-10,400)

```

###Pictograph of habitat preference

```{r}

batter <- smamms %>% 
  mutate(
    rows = case_when(
      species == 'PEMA' ~ 10,
      TRUE ~ 5
    ),
    color = case_when(
      severity == 'high' ~ 'red',
      severity == 'mod' ~ 'orange',
      severity == 'unb' ~ 'darkgreen'
    )
  ) %>% 
  filter(species == 'PEMA') # FILTER FOR SMAMM

waffled <- waffle_iron(batter, aes_d(group = color), rows = unique(batter$rows))

ggplot() +
  geom_emoji('mouse2', x = waffled$x, y = waffled$y,
             color = waffled$group,
             size = 5) +
  coord_equal() +
  ggplot2::xlim(c(-1,43)) +
  ggplot2::ylim(c(0,11)) +
  labs(x = '', y = '') +
  theme_waffle()

```

